# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Start the gpg-agent if not already running
if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
  gpg-connect-agent --daemon --use-standard-socket /bye >/dev/null 2>&1
fi

# Set SSH to use gpg-agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
fi

# Set GPG TTY
export GPG_TTY=$(tty)

# Refresh gpg-agent tty in case user switches into an X session
gpg-connect-agent updatestartuptty /bye >/dev/null

# Custom shell functions
function smux(){
    autossh -M $RANDOM $@ -t "tmux -u attach"
}
function akhal(){
    while : ; do
        clear
        khal agenda
        sleep 15
    done
}

function rsed(){
    find $1 -type f -exec sed -e $2 {} +
}

# Persistant remote connections
alias smail='smux mail'
alias irc='smux irc'

# Development aliases
alias valgrind='valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all '
alias commit='git commit'
alias pull='git pull'
alias push='git push'
alias status='git status'

# Misc
alias tmux='TERM=xterm-256color tmux -u'
#alias vim='nvim'
#alias ntvim='nvim -c "set noswapfile"'
alias open='xdg-open'
alias sl='/usr/bin/sl'
